services:
  api:
    image: ingoboerner/vebidracor-api:1.0.0 
    ports:
      - "8080:8080"
    depends_on:
      - metrics
  metrics:
    image: ingoboerner/vebidracor-metrics:1.0.0
    ports:
      - "8030:8030"
  frontend:
    image: ingoboerner/vebidracor-frontend:1.0.0
    ports:
      - "8088:80"
    depends_on:
      - api
